import {useEffect} from "react";
import fetchUsers from "../services/fetchUsers";
import MainContainer from "../components/mainContainer";
import styles from "../styles/leaders.module.css"

const App = () => {
  useEffect(async () => {
    await fetchUsers();
  }, []);

  return (
    <MainContainer keywords={'main page'}>
      <div>
        <h1 className={styles.heading}>Main Page</h1>
        <div>
          <p className={styles.paragraph}>
            Hello! This is a version of the <a href="https://github.com/233blr/ReactContacts">ReactContacts</a> application made on NextJS and ModX.
          </p>
          <p className={styles.paragraph}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Eu non diam phasellus vestibulum lorem. Turpis tincidunt id aliquet risus feugiat in ante metus. Nec ullamcorper sit amet risus nullam eget. Cras semper auctor neque vitae tempus quam. Mauris vitae ultricies leo integer malesuada nunc vel. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Sodales ut eu sem integer. Erat pellentesque adipiscing commodo elit at imperdiet. Dictum at tempor commodo ullamcorper a lacus vestibulum. Eu sem integer vitae justo eget. Praesent elementum facilisis leo vel fringilla est ullamcorper. Ornare lectus sit amet est placerat in egestas erat imperdiet.
            Tempor id eu nisl nunc mi ipsum faucibus. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. In dictum non consectetur a. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Mi bibendum neque egestas congue quisque egestas diam in arcu. Enim diam vulputate ut pharetra sit amet aliquam. Feugiat pretium nibh ipsum consequat nisl vel. A pellentesque sit amet porttitor eget dolor morbi non arcu. Dignissim sodales ut eu sem integer vitae justo eget. Velit euismod in pellentesque massa. Non odio euismod lacinia at quis risus. Neque volutpat ac tincidunt vitae semper quis lectus.
            Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Lectus mauris ultrices eros in cursus. Porttitor rhoncus dolor purus non enim praesent. Rhoncus aenean vel elit scelerisque mauris. Nulla porttitor massa id neque aliquam vestibulum morbi. Ultricies tristique nulla aliquet enim tortor. Scelerisque felis imperdiet proin fermentum. Erat imperdiet sed euismod nisi porta. Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Massa tincidunt nunc pulvinar sapien et. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Ultricies tristique nulla aliquet enim tortor at auctor urna. Elementum eu facilisis sed odio morbi quis. Et netus et malesuada fames. Nam at lectus urna duis convallis. Etiam dignissim diam quis enim lobortis scelerisque. Id leo in vitae turpis massa sed elementum tempus. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam.
            Vitae aliquet nec ullamcorper sit amet. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Sed tempus urna et pharetra pharetra massa massa ultricies. Sed pulvinar proin gravida hendrerit. Felis eget nunc lobortis mattis aliquam faucibus purus. Id interdum velit laoreet id donec ultrices. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. In aliquam sem fringilla ut morbi tincidunt augue. Nisl tincidunt eget nullam non. Porttitor eget dolor morbi non arcu. Sit amet porttitor eget dolor morbi non arcu risus. Amet porttitor eget dolor morbi non arcu risus. Eget dolor morbi non arcu. Montes nascetur ridiculus mus mauris vitae. Sagittis orci a scelerisque purus semper eget. Vitae justo eget magna fermentum iaculis eu non diam. Sed viverra tellus in hac habitasse platea dictumst vestibulum.
            Id faucibus nisl tincidunt eget nullam non nisi est sit. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Netus et malesuada fames ac turpis egestas. Sed felis eget velit aliquet sagittis id consectetur purus. Ac auctor augue mauris augue neque gravida in. Integer feugiat scelerisque varius morbi enim. Dignissim cras tincidunt lobortis feugiat vivamus. Amet purus gravida quis blandit turpis cursus in hac. Turpis massa tincidunt dui ut ornare lectus sit. Amet massa vitae tortor condimentum lacinia quis vel. Quis auctor elit sed vulputate mi sit amet mauris. Diam maecenas ultricies mi eget mauris pharetra et. Facilisis gravida neque convallis a. Cras ornare arcu dui vivamus arcu felis bibendum. Adipiscing bibendum est ultricies integer quis.
            Tincidunt dui ut ornare lectus sit. Volutpat ac tincidunt vitae semper quis. Vestibulum lorem sed risus ultricies tristique nulla. Arcu odio ut sem nulla pharetra diam. Lacus vel facilisis volutpat est velit egestas dui id ornare. Eget mi proin sed libero enim. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Adipiscing diam donec adipiscing tristique risus nec. Lacus sed viverra tellus in hac habitasse platea. Quisque egestas diam in arcu cursus. Morbi blandit cursus risus at ultrices mi tempus. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Convallis convallis tellus id interdum velit laoreet id donec ultrices.
            Eu mi bibendum neque egestas congue quisque egestas diam in. Enim tortor at auctor urna nunc id cursus metus aliquam. Vitae auctor eu augue ut lectus arcu. Nibh ipsum consequat nisl vel pretium lectus. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Risus feugiat in ante metus. Adipiscing elit duis tristique sollicitudin nibh sit amet commodo nulla. Amet aliquam id diam maecenas ultricies. Urna neque viverra justo nec ultrices dui sapien eget mi. Blandit massa enim nec dui nunc mattis enim ut tellus. Nunc vel risus commodo viverra maecenas accumsan. Laoreet non curabitur gravida arcu ac. Egestas congue quisque egestas diam in. Vitae justo eget magna fermentum iaculis eu non diam. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Nec feugiat nisl pretium fusce id velit ut. Urna cursus eget nunc scelerisque viverra mauris in.
            Tellus orci ac auctor augue mauris augue neque gravida in. Risus in hendrerit gravida rutrum quisque. Pulvinar sapien et ligula ullamcorper malesuada proin libero. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Ac tortor vitae purus faucibus ornare suspendisse. Etiam tempor orci eu lobortis elementum. In fermentum et sollicitudin ac orci phasellus egestas tellus. Turpis egestas maecenas pharetra convallis posuere morbi leo. Accumsan lacus vel facilisis volutpat est. Eget dolor morbi non arcu risus quis. Nisi porta lorem mollis aliquam ut porttitor. Ipsum nunc aliquet bibendum enim facilisis. Est ante in nibh mauris cursus mattis molestie a. Volutpat sed cras ornare arcu dui vivamus arcu. Dui ut ornare lectus sit amet est.
            Aliquam id diam maecenas ultricies mi eget mauris pharetra et. Bibendum neque egestas congue quisque egestas diam. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Praesent semper feugiat nibh sed. Non tellus orci ac auctor. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Et netus et malesuada fames ac turpis egestas sed tempus. Augue lacus viverra vitae congue eu consequat ac felis donec. Nunc vel risus commodo viverra maecenas accumsan lacus vel. Nulla facilisi nullam vehicula ipsum a arcu. Pellentesque elit eget gravida cum sociis. Mattis rhoncus urna neque viverra justo.
            Sagittis orci a scelerisque purus semper eget. At erat pellentesque adipiscing commodo. Urna duis convallis convallis tellus. Metus aliquam eleifend mi in nulla posuere. In aliquam sem fringilla ut morbi. Sit amet luctus venenatis lectus. Sodales ut eu sem integer. Velit aliquet sagittis id consectetur. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Et egestas quis ipsum suspendisse ultrices gravida. Viverra nibh cras pulvinar mattis nunc sed blandit. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui
            At consectetur lorem donec massa sapien. Mattis rhoncus urna neque viverra justo nec ultrices. Ac orci phasellus egestas tellus rutrum. Ac felis donec et odio pellentesque diam. Faucibus a pellentesque sit amet porttitor. Sapien et ligula ullamcorper malesuada. Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Eros donec ac odio tempor orci dapibus ultrices in. Vitae congue eu consequat ac felis donec et odio. Turpis egestas pretium aenean pharetra magna ac placerat. Massa eget egestas purus viverra accumsan in nisl nisi.
            Blandit massa enim nec dui nunc. Eu consequat ac felis donec et odio pellentesque. Ut eu sem integer vitae. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Interdum consectetur libero id faucibus nisl tincidunt. Mus mauris vitae ultricies leo integer malesuada. Id donec ultrices tincidunt arcu non sodales neque sodales ut. Aliquet nibh praesent tristique magna. Venenatis tellus in metus vulputate eu scelerisque felis. Massa ultricies mi quis hendrerit dolor magna eget est lorem. Diam in arcu cursus euismod. Diam vulputate ut pharetra sit amet aliquam id diam. Vivamus arcu felis bibendum ut. Posuere urna nec tincidunt praesent semper feugiat. Sapien eget mi proin sed libero. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. Feugiat in ante metus dictum. Lorem ipsum dolor sit amet consectetur adipiscing elit duis.
            Ultrices neque ornare aenean euismod elementum. Neque egestas congue quisque egestas diam in. Convallis convallis tellus id interdum velit. Integer enim neque volutpat ac tincidunt. Sed felis eget velit aliquet sagittis. Quam lacus suspendisse faucibus interdum posuere lorem. Lorem mollis aliquam ut porttitor leo a diam. Sit amet porttitor eget dolor morbi non arcu risus. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Id aliquet lectus proin nibh. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Eget felis eget nunc lobortis mattis aliquam faucibus. Eget duis at tellus at urna condimentum mattis pellentesque. Vitae proin sagittis nisl rhoncus. Aliquet risus feugiat in ante metus. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et.
            Senectus et netus et malesuada fames ac. Et tortor at risus viverra adipiscing at. Id semper risus in hendrerit gravida rutrum quisque non. Diam quam nulla porttitor massa id neque aliquam vestibulum. Diam volutpat commodo sed egestas. Duis at tellus at urna condimentum mattis pellentesque id nibh. Nisi lacus sed viverra tellus. Dolor sed viverra ipsum nunc aliquet bibendum enim. A erat nam at lectus. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Neque convallis a cras semper. Vitae nunc sed velit dignissim. Nibh venenatis cras sed felis eget velit aliquet sagittis. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Vel risus commodo viverra maecenas. Ac turpis egestas integer eget aliquet nibh. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Sollicitudin tempor id eu nisl nunc mi ipsum.
            Vel fringilla est ullamcorper eget nulla facilisi etiam. Nec dui nunc mattis enim ut. Sagittis orci a scelerisque purus semper. Et sollicitudin ac orci phasellus egestas tellus. Integer vitae justo eget magna fermentum. Enim facilisis gravida neque convallis a cras semper auctor neque. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Nibh tortor id aliquet lectus proin nibh. Amet est placerat in egestas. Integer vitae justo eget magna fermentum iaculis eu. Vel turpis nunc eget lorem dolor sed viverra ipsum. Eu ultrices vitae auctor eu augue ut. Ornare arcu odio ut sem nulla pharetra diam sit amet. Mauris a diam maecenas sed enim ut sem viverra aliquet. Sed felis eget velit aliquet sagittis. Vulputate eu scelerisque felis imperdiet proin.
            Sed nisi lacus sed viverra tellus in hac habitasse. Leo duis ut diam quam. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Bibendum enim facilisis gravida neque convallis a cras. Viverra suspendisse potenti nullam ac tortor vitae purus. Arcu cursus vitae congue mauris. Diam phasellus vestibulum lorem sed. Et tortor consequat id porta. Scelerisque fermentum dui faucibus in ornare quam. Sed risus ultricies tristique nulla aliquet. Volutpat diam ut venenatis tellus in metus vulputate. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Purus in massa tempor nec feugiat. Pretium aenean pharetra magna ac. Faucibus et molestie ac feugiat sed lectus vestibulum. Nec ullamcorper sit amet risus nullam eget felis eget. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Nibh praesent tristique magna sit amet purus gravida. In tellus integer feugiat scelerisque.
            Accumsan sit amet nulla facilisi morbi tempus. Elementum nisi quis eleifend quam adipiscing vitae proin. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Ac felis donec et odio pellentesque diam volutpat commodo. Mi proin sed libero enim sed faucibus. Pulvinar pellentesque habitant morbi tristique senectus. Malesuada fames ac turpis egestas sed tempus urna et. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Odio euismod lacinia at quis. Sed tempus urna et pharetra pharetra massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Euismod in pellentesque massa placerat duis ultricies lacus. Euismod nisi porta lorem mollis aliquam ut porttitor. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Dignissim diam quis enim lobortis. Ultrices gravida dictum fusce ut. Ante in nibh mauris cursus mattis molestie.
            Turpis egestas integer eget aliquet. Tempus urna et pharetra pharetra massa massa ultricies mi. Sit amet tellus cras adipiscing enim eu turpis egestas. Nisi est sit amet facilisis magna etiam tempor. Vitae auctor eu augue ut lectus arcu. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Morbi blandit cursus risus at. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Et ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Libero id faucibus nisl tincidunt eget nullam non nisi. Magna eget est lorem ipsum dolor sit amet consectetur. Quis commodo odio aenean sed adipiscing diam donec. Non enim praesent elementum facilisis leo vel fringilla. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Orci a scelerisque purus semper. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Ultrices neque ornare aenean euismod elementum nisi. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat.
            Cras ornare arcu dui vivamus arcu. Urna neque viverra justo nec ultrices dui sapien eget mi. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Cursus sit amet dictum sit amet justo. Massa sapien faucibus et molestie ac feugiat sed. Sed felis eget velit aliquet. Malesuada nunc vel risus commodo viverra maecenas accumsan. Turpis egestas maecenas pharetra convallis posuere. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Enim tortor at auctor urna nunc.
            Orci eu lobortis elementum nibh tellus molestie. Aliquam ut porttitor leo a diam sollicitudin tempor. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Blandit aliquam etiam erat velit. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Cras sed felis eget velit aliquet sagittis id. Nisl purus in mollis nunc sed id. Vitae suscipit tellus mauris a diam maecenas sed. Porta lorem mollis aliquam ut porttitor. Ultricies leo integer malesuada nunc vel risus commodo viverra maecenas. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Id neque aliquam vestibulum morbi blandit cursus. Dapibus ultrices in iaculis nunc sed. In vitae turpis massa sed elementum tempus egestas. Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat.
            Sed augue lacus viverra vitae congue eu. In ante metus dictum at tempor commodo ullamcorper. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. At urna condimentum mattis pellentesque id nibh tortor. Eros in cursus turpis massa tincidunt dui. Purus viverra accumsan in nisl. Gravida cum sociis natoque penatibus. Leo duis ut diam quam nulla porttitor. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum consequat. Pulvinar mattis nunc sed blandit. Velit aliquet sagittis id consectetur. Elit eget gravida cum sociis natoque. Quis viverra nibh cras pulvinar mattis nunc sed. Venenatis cras sed felis eget velit aliquet sagittis.
            Vel elit scelerisque mauris pellentesque pulvinar. Praesent tristique magna sit amet. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Arcu non sodales neque sodales ut etiam sit amet. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Vitae semper quis lectus nulla at. Ultricies mi quis hendrerit dolor. Ultrices mi tempus imperdiet nulla malesuada pellentesque. Aliquet nec ullamcorper sit amet risus nullam eget. Suspendisse interdum consectetur libero id. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. At elementum eu facilisis sed odio morbi quis commodo odio. Tincidunt augue interdum velit euismod in pellentesque massa placerat. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Amet consectetur adipiscing elit ut aliquam. Augue lacus viverra vitae congue eu consequat ac felis.
            Facilisis leo vel fringilla est ullamcorper eget. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Sagittis nisl rhoncus mattis rhoncus urna. Vulputate mi sit amet mauris commodo quis imperdiet. Praesent elementum facilisis leo vel fringilla est ullamcorper. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Interdum consectetur libero id faucibus nisl tincidunt eget nullam non. Urna et pharetra pharetra massa massa ultricies mi quis hendrerit. Turpis massa sed elementum tempus. Facilisis leo vel fringilla est ullamcorper eget.
            Vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Arcu bibendum at varius vel pharetra vel. Pretium quam vulputate dignissim suspendisse in est ante in nibh. Convallis posuere morbi leo urna. Egestas fringilla phasellus faucibus scelerisque eleifend. Interdum velit laoreet id donec ultrices. Augue neque gravida in fermentum et. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Dignissim enim sit amet venenatis urna cursus eget nunc. Tincidunt dui ut ornare lectus sit. Porttitor leo a diam sollicitudin tempor id eu nisl nunc.
            Nunc sed velit dignissim sodales. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Adipiscing diam donec adipiscing tristique risus nec. Sagittis orci a scelerisque purus semper eget duis at tellus. Sed risus ultricies tristique nulla aliquet enim. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Pulvinar pellentesque habitant morbi tristique senectus et netus. Justo nec ultrices dui sapien. Suspendisse ultrices gravida dictum fusce. Diam ut venenatis tellus in metus. Scelerisque felis imperdiet proin fermentum leo. Porttitor eget dolor morbi non. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Rhoncus urna neque viverra justo nec. Eget nulla facilisi etiam dignissim diam quis. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper.
          </p>
        </div>
      </div>
    </MainContainer>
  );
}

export default App;
